package com.ikkong.platform.controller;

import java.util.Map;
import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.platform.model.Device;
import com.ikkong.platform.service.DeviceService;
import com.ikkong.platform.service.impl.DeviceServiceImpl;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
public class DeviceController extends UrlPermissController {
	private static String CODE = "device";
	private static String PERFIX = "device";
	private static String LIST_SOURCE = "Device.list";
	private static String BASE_PATH = "/platform/device/";
	
	DeviceService service = new DeviceServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "device.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "device_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Device device = service.findById(id);
		setAttr("model", JsonKit.toJson(device));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "device_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Device device = service.findById(id);
		setAttr("model", JsonKit.toJson(device));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "device_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Device device = mapping(PERFIX, Device.class);
		boolean temp = service.save(device);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Device device = mapping(PERFIX, Device.class);
		device.setVersion(device.getVersion()+1);
		boolean temp = service.update(device);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
