package com.ikkong.platform.controller;

import java.util.Map;
import com.ikkong.core.base.BaseController;
import com.ikkong.core.jfinal.ext.kit.JsonKit;
import com.ikkong.system.controller.base.UrlPermissController;
import com.ikkong.platform.model.Version;
import com.ikkong.platform.service.VersionService;
import com.ikkong.platform.service.impl.VersionServiceImpl;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
public class VersionController extends UrlPermissController {
	private static String CODE = "version";
	private static String PERFIX = "version";
	private static String LIST_SOURCE = "Version.list";
	private static String BASE_PATH = "/platform/version/";
	
	VersionService service = new VersionServiceImpl();
	
	public void index() {
		setAttr("code", CODE);
		render(BASE_PATH + "version.html");
	}

	public void add() {
		setAttr("code", CODE);
		render(BASE_PATH + "version_add.html");
	}

	public void edit() {
		String id = getPara(0);
		Version version = service.findById(id);
		setAttr("model", JsonKit.toJson(version));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "version_edit.html");
	}

	public void view() {
		String id = getPara(0);
		Version version = service.findById(id);
		setAttr("model", JsonKit.toJson(version));
		setAttr("id", id);
		setAttr("code", CODE);
		render(BASE_PATH + "version_view.html");
	}

	public void list() {
		Object grid = paginate(LIST_SOURCE);
		renderJson(grid);
	}

	public void save() {
		Version version = mapping(PERFIX, Version.class);
		boolean temp = service.save(version);
		if (temp) {
			renderJson(success(SAVE_SUCCESS_MSG));
		} else {
			renderJson(error(SAVE_FAIL_MSG));
		}
	}

	public void update() {
		Version version = mapping(PERFIX, Version.class);
		version.setVersion(version.getVersion()+1);
		boolean temp = service.update(version);
		if (temp) {
			renderJson(success(UPDATE_SUCCESS_MSG));
		} else {
			renderJson(error(UPDATE_FAIL_MSG));
		}
	}

	public void remove() {
		String ids = getPara("ids");
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			renderJson(success(DEL_SUCCESS_MSG));
		} else {
			renderJson(error(DEL_FAIL_MSG));
		}
	}
}
