package com.ikkong.platform.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
@Table(name = "activation_code")
@BindID(name = "id")
@SuppressWarnings("serial")
public class ActivationCode extends BaseModel {
    	private Long id; //业务编号
    	private Integer activation_device_numbers; //成功激活的设备数
    	private Integer del_status; //逻辑删除状态，0为启用，1为删除
    	private Integer down_load_status; //下载状态: 0未下载 1已经下载
    	private Integer version;
    	private String activation_code; //激活码
    	private String batch_number; //批次号
    	private String descs;
    	private Long dev_related_id; //设备表关联id(关联设备表中的dev_related_id)
    	private Date create_time; //创建时间
    	private Date update_time; //修改时间

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getActivation_device_numbers() {
    		return activation_device_numbers;
    	}

    	public void setActivation_device_numbers(Integer activation_device_numbers) {
    		this.activation_device_numbers = activation_device_numbers;
    	}

    	public Integer getDel_status() {
    		return del_status;
    	}

    	public void setDel_status(Integer del_status) {
    		this.del_status = del_status;
    	}

    	public Integer getDown_load_status() {
    		return down_load_status;
    	}

    	public void setDown_load_status(Integer down_load_status) {
    		this.down_load_status = down_load_status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getActivation_code() {
    		return activation_code;
    	}

    	public void setActivation_code(String activation_code) {
    		this.activation_code = activation_code;
    	}

    	public String getBatch_number() {
    		return batch_number;
    	}

    	public void setBatch_number(String batch_number) {
    		this.batch_number = batch_number;
    	}

    	public String getDescs() {
    		return descs;
    	}

    	public void setDescs(String descs) {
    		this.descs = descs;
    	}

    	public Long getDev_related_id() {
    		return dev_related_id;
    	}

    	public void setDev_related_id(Long dev_related_id) {
    		this.dev_related_id = dev_related_id;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

    	public Date getUpdate_time() {
    		return update_time;
    	}

    	public void setUpdate_time(Date update_time) {
    		this.update_time = update_time;
    	}

}
