package com.ikkong.platform.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
@Table(name = "device")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Device extends BaseModel {
    	private Integer del_status;
    	private Integer version;
    	private String activation_code;
    	private Long dev_related_id;
    	private String device_id;
    	private String device_str;
    	private Long id;
    	private Date create_time;
    	private Date update_time;

    	@AutoID
    	public Integer getDel_status() {
    		return del_status;
    	}

    	public void setDel_status(Integer del_status) {
    		this.del_status = del_status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getActivation_code() {
    		return activation_code;
    	}

    	public void setActivation_code(String activation_code) {
    		this.activation_code = activation_code;
    	}

    	public Long getDev_related_id() {
    		return dev_related_id;
    	}

    	public void setDev_related_id(Long dev_related_id) {
    		this.dev_related_id = dev_related_id;
    	}

    	public String getDevice_id() {
    		return device_id;
    	}

    	public void setDevice_id(String device_id) {
    		this.device_id = device_id;
    	}

    	public String getDevice_str() {
    		return device_str;
    	}

    	public void setDevice_str(String device_str) {
    		this.device_str = device_str;
    	}

    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

    	public Date getUpdate_time() {
    		return update_time;
    	}

    	public void setUpdate_time(Date update_time) {
    		this.update_time = update_time;
    	}

}
