package com.ikkong.platform.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.Table;
import com.ikkong.core.annotation.BindID;
import com.ikkong.core.model.BaseModel;

import java.util.Date;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
@Table(name = "version")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Version extends BaseModel {
    	private Long id; //业务编号
    	private Integer del_status; //逻辑删除状态，0为启用，1为删除
    	private Integer version;
    	private String descs; //版本描述
    	private String version_code; //版本号
    	private Date create_time; //创建时间
    	private Date update_time; //修改时间

    	@AutoID
    	public Long getId() {
    		return id;
    	}

    	public void setId(Long id) {
    		this.id = id;
    	}

    	public Integer getDel_status() {
    		return del_status;
    	}

    	public void setDel_status(Integer del_status) {
    		this.del_status = del_status;
    	}

    	public Integer getVersion() {
    		return version;
    	}

    	public void setVersion(Integer version) {
    		this.version = version;
    	}

    	public String getDescs() {
    		return descs;
    	}

    	public void setDescs(String descs) {
    		this.descs = descs;
    	}

    	public String getVersion_code() {
    		return version_code;
    	}

    	public void setVersion_code(String version_code) {
    		this.version_code = version_code;
    	}

    	public Date getCreate_time() {
    		return create_time;
    	}

    	public void setCreate_time(Date create_time) {
    		this.create_time = create_time;
    	}

    	public Date getUpdate_time() {
    		return update_time;
    	}

    	public void setUpdate_time(Date update_time) {
    		this.update_time = update_time;
    	}

}
