package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.ActivationCode;
import com.ikkong.platform.service.ActivationCodeService;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
public class ActivationCodeServiceImpl extends BaseService<ActivationCode> implements ActivationCodeService{

}
