package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Device;
import com.ikkong.platform.service.DeviceService;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
public class DeviceServiceImpl extends BaseService<Device> implements DeviceService{

}
