package com.ikkong.platform.service.impl;

import com.ikkong.core.base.service.impl.BaseService;
import com.ikkong.platform.model.Version;
import com.ikkong.platform.service.VersionService;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
public class VersionServiceImpl extends BaseService<Version> implements VersionService{

}
