package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Device;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
public interface DeviceService extends IService<Device>{

}
