package com.ikkong.platform.service;

import com.ikkong.core.base.service.IService;
import com.ikkong.platform.model.Version;

/**
 * Generated by Blade.
 * 2017-11-21 14:13:03
 */
public interface VersionService extends IService<Version>{

}
